### PR TITLE
Text Selection refactoring of Ralph - continuation of PR #238 - fixing final tests

### PR DESCRIPTION
**Pull request by svanteschubert**
I have reviewed and continued Ralph's PR #238 

The Fix in the Nutshell:
Realized that two navigators where working on the same DOC and one was changing the DOC, but the other had a cached selection, which was not updated as the prior STATIC SelectionManager should now be moved to the OdfDocument instance to be able to dirty flag 

According to  GitHub docu - and from my understanding of it - I can only contribute to a PR, by creating a new one: 
https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

This is what I did today:

1. update my PR branch
1. Complete build of ODF Toolkit successfull on Windows 10 -> but a dozen files with Indent Normalization
1. These files changed by "Indent Normalization" committed locally to remove noise
1. The two ignored Tests activated in TextSelectionTest(@Ignore deleted) & all test output files named differently in relation to their test method 
1. does hang/loop in this TextSelectionTest in complete build.. - pasteAtEndOf causes loop
1. Enhance readablity in Tests - Making TextSelection and TextNavigation variables mnemonic, e.g. search4XY and selection4XY
1. Enhance robustness in Tests -> Exchanging global TextSelection & TextNavigation variables with local ones!
1. Fixed loop see above.

### CODE REVIEW

**Review by rsoika — APPROVED** [review]
looks all good to me

**Review by rsoika — APPROVED** [review]
yes - works now perfect!

**Review by rsoika — CHANGES_REQUESTED** [review]
Ok - I understand and yes this is a perfect solution to get away form the singleton.
But what do think about adding a method `resetSelections`
this can be necessary if user did first search and modify the doc and than - before he saves the document - what to modify the result again - now she should have the chance to reset the current selections ?

**Comment by svanteschubert** [comment]
Sure, the SelectionManager could offer such a functionality. Let me update!

**Comment by svanteschubert** [comment]
I called the method unregisterAll() as there was already a method called:
 public void unregisterItem(Selection item)

**Review by rsoika — APPROVED** [review]
looks good to me

**Pull request merged**
