### PR TITLE
ODF 1.3 new mimetype: Text master template

### PR DESCRIPTION
**Pull request by smehrbrodt**
Add validator support for ODF1.3 mimetype "application/vnd.oasis.opendocument.text-master-template" (OFFICE-2580)

### CODE REVIEW

**Comment by svanteschubert** [comment]
I am afraid this pull request is dependent on the following enhancement:
https://github.com/tdf/odftoolkit/issues/26

The complete ODFDOM is using currently solely ODF 1.2.
Like the templates that will be used, when creating an empty document are hardcoded to ODF 1.2:
https://github.com/tdf/odftoolkit/tree/1.0.0_SNAPSHOT/odfdom/src/main/resources

You can not mix ODF 1.2 with ODF 1.3 functionality unless we have transform functionality between the versions.

**Comment by mistmist** [comment]
oh... would it be possible to merge only the changes to validator and leave the odfdom as it is, or would that not work?

**Comment by svanteschubert** [comment]
Sure, validator only should work for me! :-)

**Comment by smehrbrodt** [comment]
> oh... would it be possible to merge only the changes to validator and leave the odfdom as it is, or would that not work?

Sadly that doesn't work. Produces the following error (which comes from odfdom, not validator):

`odf13_new_mimetype.odt:  Error: The ODF mimetype 'application/vnd.oasis.opendocument.text-master-template' is invalid for the ODF XML Schema document!`

**Comment by smehrbrodt** [comment]
> > oh... would it be possible to merge only the changes to validator and leave the odfdom as it is, or would that not work?
> 
> Sadly that doesn't work. Produces the following error (which comes from odfdom, not validator):
> 
> `odf13_new_mimetype.odt: Error: The ODF mimetype 'application/vnd.oasis.opendocument.text-master-template' is invalid for the ODF XML Schema document!`

So what I could do if we don't want to change odfdom, is convert this Error into a warning. That way, validation would not fail, and we can have the validator supporting 1.3 while odfdom is still on 1.2

Would that work for you?

**Comment by svanteschubert** [comment]
As discussed by phone a branch would be the best solution, as changing the error to warning would be a bug (every 'shall/must' of the ODF 1.2 specification not used is an error, every 'should' not used a warning). And adding the new mimetype in the existing ODF 1.2 ODFDOM would make it possible to create invalid ODF 1.2 with the upcoming release.

**Comment by smehrbrodt** [comment]
Closing this in favor of #43.

**Pull request closed without merging**
