### PR TITLE
Remove spurious dependencies to org.json and git-commit-id-maven plugin.

### LINKED ISSUE #142: Many unneeded compile time dependencies declared in pom.xml
In version 0.10.0, the odfdom-java package declares many dependencies which should not be needed at all, such as Maven plugins.

One can observe this with `mvn dependency:tree`:

```
[INFO] org.odftoolkit:odfdom-java:jar:0.11.0-SNAPSHOT
[INFO] +- xerces:xercesImpl:jar:2.12.1:compile
[INFO] +- xalan:serializer:jar:2.7.2:compile
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.apache.jena:jena-core:jar:4.3.0:compile
[INFO] |  +- org.apache.jena:jena-base:jar:4.3.0:compile
[INFO] |  |  +- org.apache.jena:jena-shaded-guava:jar:4.3.0:compile
[INFO] |  |  +- org.apache.commons:commons-csv:jar:1.9.0:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.11.0:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  \- com.github.andrewoma.dexx:collection:jar:0.7:compile
[INFO] |  +- org.apache.jena:jena-iri:jar:4.3.0:compile
[INFO] |  \- commons-cli:commons-cli:jar:1.5.0:compile
[INFO] +- org.apache.jena:jena-core:jar:tests:4.3.0:test
[INFO] +- net.rootdev:java-rdfa:jar:1.0.0-BETA1:compile
[INFO] +- commons-validator:commons-validator:jar:1.7:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  +- commons-digester:commons-digester:jar:2.1:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.json:json:jar:20190722:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.32:compile
[INFO] +- io.github.git-commit-id:git-commit-id-maven-plugin:jar:5.0.0:compile
[INFO] |  +- org.apache.maven:maven-plugin-api:jar:3.1.0-alpha-1:compile
[INFO] |  |  +- org.apache.maven:maven-model:jar:3.1.0-alpha-1:compile
[INFO] |  |  +- org.apache.maven:maven-artifact:jar:3.1.0-alpha-1:compile
[INFO] |  |  \- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M2a:compile
[INFO] |  |     +- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |  |     |  +- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |  |     |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  |     +- com.google.guava:guava:jar:10.0.1:compile
[INFO] |  |     +- org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[INFO] |  |     |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |     \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a:compile
[INFO] |  |        \- asm:asm:jar:3.3.1:compile
[INFO] |  +- org.apache.maven:maven-core:jar:3.1.0-alpha-1:compile
[INFO] |  |  +- org.apache.maven:maven-settings:jar:3.1.0-alpha-1:compile
[INFO] |  |  +- org.apache.maven:maven-settings-builder:jar:3.1.0-alpha-1:compile
[INFO] |  |  +- org.apache.maven:maven-repository-metadata:jar:3.1.0-alpha-1:compile
[INFO] |  |  +- org.apache.maven:maven-model-builder:jar:3.1.0-alpha-1:compile
[INFO] |  |  +- org.apache.maven:maven-aether-provider:jar:3.1.0-alpha-1:compile
[INFO] |  |  |  \- org.eclipse.aether:aether-spi:jar:0.9.0.M2:compile
[INFO] |  |  +- org.eclipse.aether:aether-impl:jar:0.9.0.M2:compile
[INFO] |  |  +- org.eclipse.aether:aether-api:jar:0.9.0.M2:compile
[INFO] |  |  +- org.eclipse.aether:aether-util:jar:0.9.0.M2:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.16:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-utils:jar:3.0.10:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.4.2:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[INFO] |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[INFO] |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] |  +- io.github.git-commit-id:git-commit-id-plugin-core:jar:5.0.0:compile
[INFO] |  |  +- org.eclipse.jgit:org.eclipse.jgit:jar:5.12.0.202106070339-r:compile
[INFO] |  |  |  \- com.googlecode.javaewah:JavaEWAH:jar:1.1.7:compile
[INFO] |  |  +- org.eclipse.jgit:org.eclipse.jgit.ssh.jsch:jar:5.12.0.202106070339-r:compile
[INFO] |  |  |  +- com.jcraft:jsch:jar:0.1.55:compile
[INFO] |  |  |  \- com.jcraft:jzlib:jar:1.1.1:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.10.10:compile
[INFO] |  |  +- org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
[INFO] |  |  +- nu.studer:java-ordered-properties:jar:1.0.4:compile
[INFO] |  |  +- javax.json:javax.json-api:jar:1.1.4:compile
[INFO] |  |  \- org.glassfish:javax.json:jar:1.1.4:compile
[INFO] |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] \- org.apache.commons:commons-compress:jar:1.21:compile

```

### PR DESCRIPTION
**Pull request by wetneb**
Fixes #142.

New dependencies:
```
[INFO] org.odftoolkit:odfdom-java:jar:0.11.0-SNAPSHOT
[INFO] +- xerces:xercesImpl:jar:2.12.1:compile
[INFO] +- xalan:serializer:jar:2.7.2:compile
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.apache.jena:jena-core:jar:4.3.0:compile
[INFO] |  +- org.apache.jena:jena-base:jar:4.3.0:compile
[INFO] |  |  +- org.apache.jena:jena-shaded-guava:jar:4.3.0:compile
[INFO] |  |  +- org.apache.commons:commons-csv:jar:1.9.0:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.11.0:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  \- com.github.andrewoma.dexx:collection:jar:0.7:compile
[INFO] |  +- org.apache.jena:jena-iri:jar:4.3.0:compile
[INFO] |  \- commons-cli:commons-cli:jar:1.5.0:compile
[INFO] +- org.apache.jena:jena-core:jar:tests:4.3.0:test
[INFO] +- net.rootdev:java-rdfa:jar:1.0.0-BETA1:compile
[INFO] +- commons-validator:commons-validator:jar:1.7:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  +- commons-digester:commons-digester:jar:2.1:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.32:compile
[INFO] \- org.apache.commons:commons-compress:jar:1.21:compile
```

### CODE REVIEW

**Comment by wetneb** [comment]
Aargh, this library actually depends on `org.json`, that dependency was not spurious. This has a license that is not OSI-compliant. I'll open a separate issue about this.

**Comment by wetneb** [comment]
Issue about the dependency to org.json: https://github.com/tdf/odftoolkit/issues/144

**Comment by svanteschubert** [comment]
We might change/add 
            <groupId>io.github.git-commit-id</groupId>
to a test dependency.

The reason for this dependency:
During building the current GIT commit hash is being extracted and placed into the manifest to be read out whenever a "java -jar odfdom<XY>.jar is being called to be certain when similar behaviour can be expected from ODFDOM JARs. 
But yes, this GIT extraction functionality is not required during run-time. Indeed a bug!

**Comment by wetneb** [comment]
Well, if the tests pass without this dependency, I do not think we need to add this artifact as a test dependency. Maven can use it as part of the build process already, since it is declared as a plugin.

**Review by svanteschubert — APPROVED** [review]
Good catch, Antonin! And many thanks for your quick patch!
Cheers,
Svante

**Pull request merged**
